// <auto-generated />
namespace ConsultaMed_WEB.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Atualizacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Atualizacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201304172351105_Atualizacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
