// <auto-generated />
namespace ConsultaMed_WEB.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EmailClinica2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailClinica2));
        
        string IMigrationMetadata.Id
        {
            get { return "201303200004255_EmailClinica2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
