//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaMed_ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinica
    {
        public Clinica()
        {
            this.Usuario = new HashSet<Usuario>();
            this.Convenio = new HashSet<Convenio>();
        }
    
        public int ClinicaId { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Site { get; set; }
        public string HorarioAtendimento { get; set; }
        public int EnderecoId { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual ICollection<Convenio> Convenio { get; set; }
        public virtual Endereco Endereco { get; set; }
    }
}
