//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaMed_ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public Endereco()
        {
            this.Clinica = new HashSet<Clinica>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int EnderecoId { get; set; }
        public string Rua { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public int Numero { get; set; }
        public string Complemento { get; set; }
        public string Cep { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<Clinica> Clinica { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
