//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaMed_ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exame
    {
        public Exame()
        {
            this.Prontuario = new HashSet<Prontuario>();
        }
    
        public int ExameId { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Prontuario> Prontuario { get; set; }
    }
}
