//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaMed_ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prontuario
    {
        public int ProntuarioId { get; set; }
        public string Descricao { get; set; }
        public int ExameId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DataCriacao { get; set; }
    
        public virtual Exame Exame { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
