//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaMed_ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Agendamento = new HashSet<Agendamento>();
            this.Agendamento1 = new HashSet<Agendamento>();
            this.Horario = new HashSet<Horario>();
            this.HorarioTemp = new HashSet<HorarioTemp>();
            this.Prontuario = new HashSet<Prontuario>();
        }
    
        public int UserId { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Cpf { get; set; }
        public string Rg { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public int ClinicaId { get; set; }
        public Nullable<int> ConvenioId { get; set; }
        public int EnderecoId { get; set; }
        public string Crm { get; set; }
        public Nullable<int> EspecialidadeId { get; set; }
        public string NumeroConvenio { get; set; }
        public string Discriminator { get; set; }
        public string Perfil { get; set; }
    
        public virtual ICollection<Agendamento> Agendamento { get; set; }
        public virtual ICollection<Agendamento> Agendamento1 { get; set; }
        public virtual Clinica Clinica { get; set; }
        public virtual Convenio Convenio { get; set; }
        public virtual Endereco Endereco { get; set; }
        public virtual Especialidade Especialidade { get; set; }
        public virtual ICollection<Horario> Horario { get; set; }
        public virtual ICollection<HorarioTemp> HorarioTemp { get; set; }
        public virtual ICollection<Prontuario> Prontuario { get; set; }
    }
}
